version: '3.8'

networks:
  isp-net:
    driver: bridge

services:

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - isp-net

  webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    container_name: webmail
    networks:
      - isp-net

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: portal
    networks:
      - isp-net

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_reverse
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dns
      - webmail
      - portal
      - proxy1
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isp-net

  proxy1:
    image: nginx:alpine
    container_name: proxy1
    depends_on:
      - portal_c1
      - hotsite_c1
      - sign_c1
    volumes:
      - ./cliente1/proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isp-net

  portal_c1:
    image: nginx:alpine
    container_name: portal_c1
    networks:
      - isp-net
    volumes:
      - ./cliente1/portal:/usr/share/nginx/html

  hotsite_c1:
    image: nginx:alpine
    container_name: hotsite_c1
    networks:
      - isp-net
    volumes:
      - ./cliente1/hotsite:/usr/share/nginx/html

  sign_c1:
    image: nginx:alpine
    container_name: sign_c1
    networks:
      - isp-net
    volumes:
      - ./cliente1/sign:/usr/share/nginx/html
