version: '3.8'

services: 
  wordpress:
    image: wordpress:latest
    restart: always
    ports: 
      - 8080:80
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes: 
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports: 
      - 8888:8080

volumes:
  wordpress_data:
