version: '3.8'

services:
  proxy1:
    image: nginx:alpine
    container_name: proxy1
    networks:
      - isp-net
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  portal_c1:
    image: nginx:alpine
    container_name: portal_c1
    networks:
      - isp-net
    volumes:
      - ../portal:/usr/share/nginx/html

  hotsite_c1:
    image: nginx:alpine
    container_name: hotsite_c1
    networks:
      - isp-net
    volumes:
      - ../hotsite:/usr/share/nginx/html

  sign_c1:
    image: nginx:alpine
    container_name: sign_c1
    networks:
      - isp-net
    volumes:
      - ../sign:/usr/share/nginx/html

networks:
  isp-net:
    external: true
