version: '3.8'

services:
  ### Proxy do Cliente 3 ###
  proxy3:
    image: nginx:alpine
    container_name: proxy3
    depends_on:
      - portal_c3
      - wordpress
      - db
      - adminer
    ports:
      - "8001:80" # Para testes locais
    networks:
      - memorial_net
      - parnamac_net
    volumes:
      - ./proxy3/default.conf:/etc/nginx/conf.d/default.conf

  ### Portal ###
  portal_c3:
    image: nginx:alpine
    container_name: portal_c3
    networks:
      - memorial_net
    volumes:
      - ./portal:/usr/share/nginx/html

  ### CMS ###
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    networks:
      - memorial_net
    volumes:
      - ./site:/var/www/html # Usa os arquivos exportados

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - memorial_net
    volumes:
      - db_data:/var/lib/mysql # persiste o banco

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - memorial_net
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:


networks:
  memorial_net:
    external: true
  parnamac_net:
    external: true
