version: '3.8'

services:

  proxy:
    build: .
    container_name: proxy-reverse
    ports:
      - "80:80"
      - "443:443"
    networks:
      - isp-net
    depends_on:
      - webmail
      - portal
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  webmail:
    image: nginx:alpine
    container_name: webmail
    networks:
      - isp-net
    volumes:
      - ./webmail:/usr/share/nginx/html

  portal:
    image: nginx:alpine
    container_name: portal
    networks:
      - isp-net
    volumes:
      - ./portal:/usr/share/nginx/html

networks:
  isp-net:
    driver: bridge
