version: '3.8'

services:
  ### Proxy do Cliente 2 ###
  proxy2:
    image: nginx:alpine
    container_name: proxy2
    depends_on:
      - portal_c2
      - cms
    ports:
      - "8002:80" # Para testes locais
    networks:
      - macau_net
      - parnamac_net
    volumes:
      - ./proxy2/default.conf:/etc/nginx/conf.d/default.conf

  ### Portal ###
  portal_c2:
    image: nginx:alpine
    container_name: portal_c2
    networks:
      - macau_net
    volumes:
      - ./portal:/usr/share/nginx/html

  ### CMS ###
  cms:
    image: nginx:alpine
    container_name: cms
    networks:
      - macau_net
    volumes:
      - ./cms:/usr/share/nginx/html

networks:
  macau_net:
    external: true
  parnamac_net:
    external: true
