version: '3.8'

services:
  ### Proxy do Cliente 2 ###
  proxy2:
    image: nginx:alpine
    container_name: proxy2
    depends_on:
      - portal_c2
      - wordpress
      - db
      - adminer
    networks:
      - macau_net
      - parnamac_net
    volumes:
      - ./proxy2/default.conf:/etc/nginx/conf.d/default.conf

  ### Portal ###
  portal_c2:
    image: nginx:alpine
    container_name: portal_c2
    networks:
      - macau_net
    volumes:
      - ./portal:/usr/share/nginx/html

  ### CMS (WordPress) ###
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    networks:
      - macau_net
    volumes:
      - ./site:/var/www/html # Usa os arquivos exportados

  ### Banco de Dados do CMS ###
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - macau_net
    volumes:
      - db_data:/var/lib/mysql # persiste o banco

  ### Adminer (opcional, para gerenciar o banco) ###
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9999:8080
    networks:
      - macau_net
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db_data:


networks:
  macau_net:
    external: true
  parnamac_net:
    external: true
